version: "3.8"

services:
  web:
    image: cosmtrek/air
    working_dir: /app
    ports:
      - 4000:4000
    volumes:
      - ./:/app
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tournajay
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
